# Generated by Django 4.2.1 on 2023-07-28 21:48

import django.core.validators
from django.db import migrations
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=users.models.PhoneNumberField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "(((\\+|00)(98))|0)?9\\d{2}-?\\d{3}-?\\d{4}"
                    )
                ],
            ),
        ),
    ]
