# Generated by Django 4.2.1 on 2023-08-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
        ("orders", "0002_order_responsible_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="foods.food"
            ),
        ),
    ]
