# Generated by Django 4.2.3 on 2023-08-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
