# Generated by Django 4.2.1 on 2023-08-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analytics_refresh", models.PositiveIntegerField(default=0,help_text="hours needed to get analytics data from database again")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
